services:

    mysql:
        build: ./mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'MENU'
            MYSQL_USER: 'usuario'
            MYSQL_PASSWORD: 'usuario'
        volumes:
            - db-volume:/var/lib/mysql
        networks:
            - red

    php:
        build: ./php
        depends_on:
            - mysql
        ports:
            - 80:80
        volumes:
            - ./php/.htaccess:/var/www/html/php/.htaccess
            - ./php:/var/www/html/php
        networks:
            - red

volumes:
    db-volume:


networks:
    red:
